# Generated by Django 4.2.3 on 2023-07-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'marks',
                'db_table': 'mark',
            },
        ),
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name_plural': 'upload_files',
                'db_table': 'upload_file',
            },
        ),
        migrations.CreateModel(
            name='Upload_File2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files2/')),
            ],
            options={
                'verbose_name_plural': 'upload_files2',
                'db_table': 'upload_file2',
            },
        ),
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='basic_app.mark')),
            ],
            options={
                'verbose_name_plural': 'models',
                'db_table': 'model1',
            },
        ),
    ]
