# Generated by Django 4.2.3 on 2023-07-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data22Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file2')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data22', to='basic_app.model1')),
            ],
            options={
                'verbose_name_plural': 'data22',
                'db_table': 'data22',
            },
        ),
        migrations.CreateModel(
            name='Data21Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data21', to='basic_app.model1')),
            ],
            options={
                'verbose_name_plural': 'data21',
                'db_table': 'data21',
            },
        ),
    ]
