# Generated by Django 4.2.3 on 2023-07-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_data22data_data21data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data21Data',
            new_name='Data21',
        ),
        migrations.RenameModel(
            old_name='Data22Data',
            new_name='Data22',
        ),
    ]
