# Generated by Django 4.2.3 on 2023-07-25 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_rename_data21data_data21_rename_data22data_data22'),
    ]

    operations = [
        migrations.AddField(
            model_name='data21',
            name='time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='data22',
            name='time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
