# Generated by Django 4.2.3 on 2023-07-25 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_data21_time_data22_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data21',
            name='time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='data yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='data22',
            name='time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='data yaratilgan vaqti'),
        ),
    ]
